### ISSUE TITLE
How does thredds swarming work?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/data-life-cycle-cloud-docker-thredds#2]
@isuftin, I read the [README.md](https://github.com/USGS-CMG/data-life-cycle-cloud-docker-thredds/blob/master/README.md), but I've never heard of a swarm of THREDDS servers, so I'm curious how this works.   Does this mean there is a single THREDDS endpoint, but that 10 requests coming in at the same time to that endpoint could get handled by 10 different servers that are all configured identically?  And would they all share the same cache and log files?

**Comment by rsignell-usgs** [comment]
CC @julienchastang

**Comment by isuftin** [comment]
@rsignell-usgs Swarming for THREDDS would indeed have a single THREDDS endpoint, but the client request is handled by the Swarm mesh network. The request is routed to any available THREDDS server. The THREDDS servers, unless they are on the same machine, would not be sharing the same cache and log files unless they are mounted to a remote service that provides that sort of storage space. Each THREDDS server would be fully encapsulated as its own process. 

If the log files are being written to a network location or a log location served by something like NFS,  they may all write to a single location but they would not want to write to the same exact log file. Another option is to have them write to syslog and have a higher-level log aggregator like an ELK stack running to collect and merge those logs into a single stream

I'm not too clear on how THREDDS caching works so I'm not able to answer your question in regards to that but a similar service topology would preferably be used if sharing a single cache location is desired.

**Comment by rsignell-usgs** [comment]
According to offline conversations with @kwilcox , he thinks it unlikely we will need a swarm, because he says THREDDS doesn't have a problem handling a large number of requests.   It will be interesting to test though.

**Comment by isuftin** [comment]
@rsignell-usgs No worries. My main goal here was to proof that it can be done via Swarm since that's where we'd be deploying to. Having a Swarm service with a count of 1 is also fine.

**Comment by rsignell-usgs** [comment]
Okay, cool!
